c_app/product/models.py
PRODUCTS = {
    'men':{
        'name':'khaki',
        'category':'trousers',
        'price': 7,
    },
    'ladies':{
        'name':'palazo pants',
        'category':'trousers',
        'price':12,
    },
    'kids':{
        'name':'kids jeans',
        'category':'trousers',
        'price':5,
    },
    'ubuntu-phone':{
        'name':'ubuntu phone',
        'category':'phones',
        'price':400,
    },
    'iphones':{
        'name':'iphone-x',
        'category':'phones',
        'price':1200,
    }
}

c_app/__init__.py
from locale import currency
import ccy
from flask import Flask, request
from c_app.product.views import fashion

app = Flask(__name__)
app.register_blueprint(fashion)

@app.template_filter('format_currency')
def format_currency_filter(amount):
    currency_code = ccy.countryccy(request.accept_languages.best[-2:])
    return f'{currency_code} {amount}'

c_app/product/__init__.py
#package purposes:

c_app/product/views.py
#from werkzeug import abort
from flask import Blueprint, render_template,abort
from c_app.product.models import PRODUCTS

fashion = Blueprint('fashion', __name__)

@fashion.route('/')
@fashion.route('/home')
def home():
    return render_template('home.html', products=PRODUCTS)

@fashion.route('/product/<key>')
def product(key):
    product = PRODUCTS.get(key)
    if not product:
        abort(404)
    return render_template('product.html', product=product)

@fashion.context_processor
def product_name_processor():
    def full_name(product):
        return f'{product["name"]}/{product["category"]}'
    return dict(full_name=full_name)

c_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Oeri Fashio Designs</title>
<!-- Optional theme -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link href="{{ url_for('static', filename='css/main.css') }}"rel="stylesheet">
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top"role="navigation">
<div class="container">
<div class="navbar-header">
<a class="navbar-brand" href="{{ url_for('fashion.home')}}">Oeri Designs</a>
</div>
</div>
</div>
<div class="container">
{% block container %}{% endblock %}
</div>
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
<!-- Latest compiled and minified JavaScript -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>

c_app/templates/home.html
{% extends 'base.html' %}

{% block container %}
<div class="top-pad">
{% for id, product in products.items() %}
<div class="well">
    <h2>
    <a href="{{ url_for('fashion.product', key=id) }}">{{ product['name'] }}</a>
    <small> {{ product['price'] | format_currency}}</small>
    </h2>
    </div>
    {% endfor %}
    </div>
    {% endblock %}

c_app/templates/product.html
{% extends 'home.html' %}
{% block container %}
<div class="top-pad">
<h4>{{ full_name(product) }}</h4>
<h1>{{ product['name'] }}
<small>{{ product['category'] }}</small>
</h1>
<h3> {{ product['price'] | format_currency }}</h3>
</div>
{% endblock %}  